# Generated by Django 3.1.5 on 2021-09-10 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('peopleAmount', models.IntegerField()),
                ('electricityUsed', models.IntegerField()),
                ('electricityGreen', models.IntegerField(default=1)),
                ('gasUsed', models.IntegerField()),
                ('heatingGasUsed', models.BooleanField()),
                ('heatingOilUsed', models.IntegerField()),
                ('coalUsed', models.IntegerField()),
                ('woodUsed', models.IntegerField()),
                ('bottledGasUsed', models.IntegerField()),
                ('carsAmount', models.IntegerField()),
                ('carOneSize', models.IntegerField()),
                ('carOneMileage', models.IntegerField()),
                ('carTwoSize', models.IntegerField()),
                ('carTwoMileage', models.IntegerField()),
                ('carThreeSize', models.IntegerField()),
                ('carThreeMileage', models.IntegerField()),
                ('carFourSize', models.IntegerField()),
                ('carFourMileage', models.IntegerField()),
                ('organicFoodAmount', models.DecimalField(decimal_places=2, max_digits=6)),
                ('meatDairyAmount', models.DecimalField(decimal_places=2, max_digits=6)),
                ('localFoodAmount', models.DecimalField(decimal_places=2, max_digits=6)),
                ('packagedFoodAmount', models.DecimalField(decimal_places=2, max_digits=6)),
                ('compostFoodAmount', models.DecimalField(decimal_places=2, max_digits=6)),
                ('foodWasteAmount', models.DecimalField(decimal_places=2, max_digits=6)),
                ('mileageEachWeekBus', models.IntegerField()),
                ('mileageEachWeekTrain', models.IntegerField()),
                ('hoursSpentFlying', models.IntegerField()),
                ('miscSpending', models.DecimalField(decimal_places=2, default=3.4, max_digits=6)),
                ('recyclePGM', models.DecimalField(decimal_places=2, max_digits=6)),
                ('recyclePlastic', models.DecimalField(decimal_places=2, max_digits=6)),
            ],
        ),
    ]
