# Generated by Django 3.1.5 on 2021-09-10 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('footprint', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='bottledGasUsed',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='carFourMileage',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='carFourSize',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='carOneMileage',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='carOneSize',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='carThreeMileage',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='carThreeSize',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='carTwoMileage',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='carTwoSize',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='carsAmount',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='post',
            name='coalUsed',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='compostFoodAmount',
            field=models.DecimalField(decimal_places=2, default=0.2, max_digits=6),
        ),
        migrations.AlterField(
            model_name='post',
            name='electricityUsed',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='foodWasteAmount',
            field=models.DecimalField(decimal_places=2, default=0.5, max_digits=6),
        ),
        migrations.AlterField(
            model_name='post',
            name='gasUsed',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='heatingGasUsed',
            field=models.BooleanField(default=0),
        ),
        migrations.AlterField(
            model_name='post',
            name='heatingOilUsed',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='hoursSpentFlying',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='localFoodAmount',
            field=models.DecimalField(decimal_places=2, default=0.1, max_digits=6),
        ),
        migrations.AlterField(
            model_name='post',
            name='meatDairyAmount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6),
        ),
        migrations.AlterField(
            model_name='post',
            name='mileageEachWeekBus',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='mileageEachWeekTrain',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='organicFoodAmount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6),
        ),
        migrations.AlterField(
            model_name='post',
            name='packagedFoodAmount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6),
        ),
        migrations.AlterField(
            model_name='post',
            name='recyclePGM',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6),
        ),
        migrations.AlterField(
            model_name='post',
            name='recyclePlastic',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6),
        ),
        migrations.AlterField(
            model_name='post',
            name='woodUsed',
            field=models.IntegerField(blank=True),
        ),
    ]
