# Generated by Django 3.1.5 on 2021-09-11 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('footprint', '0003_auto_20210910_2211'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='bottledGasUsed',
            field=models.IntegerField(blank=True, verbose_name=' რა რაოდენობის ჩამოსხმული გაზი გამოიყენეთ გასული წლის განმავლობაში (კილოგრამებში)'),
        ),
        migrations.AlterField(
            model_name='post',
            name='carFourMileage',
            field=models.IntegerField(blank=True, choices=[(6000, 'დაბალი (10000 კმ)'), (9000, 'საშუალო (15000 კმ)'), (12000, 'მაღალი (20000 კმ)')], default=0, null=True, verbose_name=' მანქანა 4 გარბენი:'),
        ),
        migrations.AlterField(
            model_name='post',
            name='carFourSize',
            field=models.IntegerField(blank=True, choices=[(35, 'სპორტული მანქანა ან დიდი ჯიპი'), (46, 'პატარა/საშუალო ზომის ჯიპი ან მინივენი'), (52, 'პატარა, საშუალო ან დიდი უნივერსალი')], default=1, null=True, verbose_name=' მანქანა 4 ზომა:'),
        ),
        migrations.AlterField(
            model_name='post',
            name='carOneMileage',
            field=models.IntegerField(blank=True, choices=[(6000, 'დაბალი (10000 კმ)'), (9000, 'საშუალო (15000 კმ)'), (12000, 'მაღალი (20000 კმ)')], default=0, null=True, verbose_name=' მანქანა 1 გარბენი:'),
        ),
        migrations.AlterField(
            model_name='post',
            name='carOneSize',
            field=models.IntegerField(blank=True, choices=[(35, 'სპორტული მანქანა ან დიდი ჯიპი'), (46, 'პატარა/საშუალო ზომის ჯიპი ან მინივენი'), (52, 'პატარა, საშუალო ან დიდი უნივერსალი')], default=1, null=True, verbose_name=' მანქანა 1 ზომა:'),
        ),
        migrations.AlterField(
            model_name='post',
            name='carThreeMileage',
            field=models.IntegerField(blank=True, choices=[(6000, 'დაბალი (10000 კმ)'), (9000, 'საშუალო (15000 კმ)'), (12000, 'მაღალი (20000 კმ)')], default=0, null=True, verbose_name=' მანქანა 3 გარბენი:'),
        ),
        migrations.AlterField(
            model_name='post',
            name='carThreeSize',
            field=models.IntegerField(blank=True, choices=[(35, 'სპორტული მანქანა ან დიდი ჯიპი'), (46, 'პატარა/საშუალო ზომის ჯიპი ან მინივენი'), (52, 'პატარა, საშუალო ან დიდი უნივერსალი')], default=1, null=True, verbose_name=' მანქანა 3 ზომა:'),
        ),
        migrations.AlterField(
            model_name='post',
            name='carTwoMileage',
            field=models.IntegerField(blank=True, choices=[(6000, 'დაბალი (10000 კმ)'), (9000, 'საშუალო (15000 კმ)'), (12000, 'მაღალი (20000 კმ)')], default=0, null=True, verbose_name=' მანქანა 2 გარბენი:'),
        ),
        migrations.AlterField(
            model_name='post',
            name='carTwoSize',
            field=models.IntegerField(blank=True, choices=[(35, 'სპორტული მანქანა ან დიდი ჯიპი'), (46, 'პატარა/საშუალო ზომის ჯიპი ან მინივენი'), (52, 'პატარა, საშუალო ან დიდი უნივერსალი')], default=1, null=True, verbose_name=' მანქანა 2 ზომა:'),
        ),
        migrations.AlterField(
            model_name='post',
            name='carsAmount',
            field=models.IntegerField(choices=[(0, '0'), (1, '1'), (2, '2'), (3, '3'), (4, '4')], default=0, verbose_name=' რამდენი მანქანაა თქვენ ოჯახში?'),
        ),
        migrations.AlterField(
            model_name='post',
            name='coalUsed',
            field=models.IntegerField(blank=True, verbose_name=' რა რაოდენობის ქვანახშირი გამოიყენეთ გასული წლის განმავლობაში (კილოგრამებში)'),
        ),
        migrations.AlterField(
            model_name='post',
            name='compostFoodAmount',
            field=models.DecimalField(choices=[(2, 'არასდროს'), (1, 'ხანდახან'), (0, 'ყოველთვის')], decimal_places=2, default=0.2, max_digits=6, null=True, verbose_name=' რამდენად უკეთებთ კომპოსტირებას ნარჩენ და გამოუყენებელ საკვებს?'),
        ),
        migrations.AlterField(
            model_name='post',
            name='electricityGreen',
            field=models.IntegerField(choices=[(100, 'არა'), (75, 'დიახ')], default=1, verbose_name=' იყენებთ თუ არა მწვანე ენერგიას?'),
        ),
        migrations.AlterField(
            model_name='post',
            name='electricityUsed',
            field=models.IntegerField(blank=True, choices=[(3000, 'პატარა ზომის სახლი / ბინა (3000 კვტ/სთ)'), (4800, 'საშუალო ზომის სახლი (4800 კვტ/სთ)'), (7000, 'დიდი ზომის სახლი (7000 კვტ/სთ)'), (2000, 'დარბაზული სახლი (2000 კვტ/სთ)')], null=True, verbose_name=' რა რაოდენობით დენი მოიხმარება თქვენ სახლში?'),
        ),
        migrations.AlterField(
            model_name='post',
            name='foodWasteAmount',
            field=models.DecimalField(choices=[(148, 'დიდი რაოდენობა'), (125, 'საშუალო რაოდენობა'), (103, 'მცირე რაოდენობა'), (86, 'ძალიან მცირე')], decimal_places=2, default=0.5, max_digits=6, null=True, verbose_name=' რა რაოდენობით საკვებს ფლანგავთ?'),
        ),
        migrations.AlterField(
            model_name='post',
            name='gasUsed',
            field=models.IntegerField(blank=True, choices=[(12000, 'პატარა ზომის სახლი / ბინა (12000 კვტ/სთ)'), (18000, 'საშუალო ზომის სახლი (18000 კვტ/სთ)'), (27000, 'დიდი ზომის სახლი (27000 კვტ/სთ)'), (5000, 'დარბაზული სახლი (5000 კვტ/სთ)')], default=0, null=True, verbose_name=' რა რაოდენობით გაზი მოიხმარება თქვენ სახლში?'),
        ),
        migrations.AlterField(
            model_name='post',
            name='heatingGasUsed',
            field=models.BooleanField(choices=[(0, 'არა'), (1, 'დიახ')], default=0, verbose_name=' გამოიყენება თუ არა თქვენ სახლში ზეთი, ქვანახშირი, შეშა ან ჩამოსხმული გაზი გასათბობად?'),
        ),
        migrations.AlterField(
            model_name='post',
            name='heatingOilUsed',
            field=models.IntegerField(blank=True, verbose_name=' რა რაოდენობის ზეთი გამოიყენეთ გასული წლის განმავლობაში (ლიტრებში)'),
        ),
        migrations.AlterField(
            model_name='post',
            name='hoursSpentFlying',
            field=models.IntegerField(blank=True, null=True, verbose_name=' წელიწადში რამდენ საათს ატარებთ თვითმფრინავში?'),
        ),
        migrations.AlterField(
            model_name='post',
            name='localFoodAmount',
            field=models.DecimalField(choices=[(5, 'ძალიან მცირე'), (3, 'საშუალო'), (2, 'საშუალოზე მეტი'), (1, 'თითქმის მთლიანად')], decimal_places=2, default=3, max_digits=6, null=True, verbose_name=' თქვენი საკვების რა ნაწილია წარმოებული ადგილობრივად?'),
        ),
        migrations.AlterField(
            model_name='post',
            name='meatDairyAmount',
            field=models.DecimalField(blank=True, choices=[(60, 'საშუალოზე მეტს'), (40, 'საშუალო რაოდენობას'), (25, 'საშუალოზე ნაკლებს'), (10, 'არ მივირთმევ ხორცს'), (0, 'არ მივირთმევ არც ხორცს და არც რძეს')], decimal_places=2, default=40, max_digits=6, null=True, verbose_name=' რა რაოდენობით მიირთმევთ ხორცს ან/და რძეს?'),
        ),
        migrations.AlterField(
            model_name='post',
            name='mileageEachWeekBus',
            field=models.IntegerField(blank=True, null=True, verbose_name=' კვირაში რამდენ კილომეტრს მგზავრობთ ავტობუსით?'),
        ),
        migrations.AlterField(
            model_name='post',
            name='mileageEachWeekTrain',
            field=models.IntegerField(blank=True, null=True, verbose_name=' კვირაში რამდენ კილომეტრს მგზავრობთ მატარებლით?'),
        ),
        migrations.AlterField(
            model_name='post',
            name='miscSpending',
            field=models.DecimalField(choices=[(50, 'დიდი რაოდენობა'), (34, 'საშუალო რაოდენობა'), (24, 'მცირე რაოდენობა'), (14, 'ძალიან მცირე')], decimal_places=2, default=34, max_digits=6, null=True, verbose_name=' რა რაოდენობით ფულს ხარჯავთ სხვადასხვა ხარჯებში?'),
        ),
        migrations.AlterField(
            model_name='post',
            name='organicFoodAmount',
            field=models.DecimalField(blank=True, choices=[(7, 'არასდროს'), (5, 'ხანდახან'), (2, 'უმეტესად'), (0, 'ყოველთვის')], decimal_places=2, default=7, max_digits=6, null=True, verbose_name=' რა რაოდენობით მიირთმევთ ორგანულ საკვებს'),
        ),
        migrations.AlterField(
            model_name='post',
            name='packagedFoodAmount',
            field=models.DecimalField(blank=True, choices=[(60, 'დიდი რაოდენობა'), (40, 'საშუალო რაოდენობა'), (20, 'მცირე რაოდენობა'), (5, 'ძალიან მცირე')], decimal_places=2, default=0, max_digits=6, null=True, verbose_name=' თქვენი საკვების რა ნაწილია შეფუთული?'),
        ),
        migrations.AlterField(
            model_name='post',
            name='peopleAmount',
            field=models.IntegerField(verbose_name=' რამდენი ადამიანი ცხოვრობს თქვენთან სახლში? (თქვენ ჩათვლით)'),
        ),
        migrations.AlterField(
            model_name='post',
            name='recyclePGM',
            field=models.DecimalField(blank=True, choices=[(0, 'არა'), (7, 'დიახ')], decimal_places=2, default=0, max_digits=6, null=True, verbose_name=' აკეთებთ თუ არა ქაღალდს, მინას და ლითონს გადამუშავებას?'),
        ),
        migrations.AlterField(
            model_name='post',
            name='recyclePlastic',
            field=models.DecimalField(blank=True, choices=[(0, 'არა'), (14, 'დიახ')], decimal_places=2, default=0, max_digits=6, null=True, verbose_name=' აკეთებთ თუ არა პლასტმასის გადამუშავებას გარდა პოლიეთილენის პარკების?'),
        ),
        migrations.AlterField(
            model_name='post',
            name='woodUsed',
            field=models.IntegerField(blank=True, verbose_name=' რა რაოდენობის შეშა გამოიყენეთ გასული წლის განმავლობაში (კილოგრამებში)'),
        ),
    ]
