# Generated by Django 3.1.5 on 2021-09-11 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('footprint', '0004_auto_20210911_1523'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='heatingOilUsed',
            field=models.IntegerField(blank=True, null=True, verbose_name=' რა რაოდენობის ზეთი გამოიყენეთ გასული წლის განმავლობაში (ლიტრებში)'),
        ),
    ]
