# Generated by Django 3.1.5 on 2021-09-11 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('footprint', '0005_auto_20210911_1524'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='bottledGasUsed',
            field=models.IntegerField(blank=True, null=True, verbose_name=' რა რაოდენობის ჩამოსხმული გაზი გამოიყენეთ გასული წლის განმავლობაში (კილოგრამებში)'),
        ),
        migrations.AlterField(
            model_name='post',
            name='carsAmount',
            field=models.IntegerField(choices=[(0, '0'), (1, '1'), (2, '2'), (3, '3'), (4, '4')], default=0, null=True, verbose_name=' რამდენი მანქანაა თქვენ ოჯახში?'),
        ),
        migrations.AlterField(
            model_name='post',
            name='coalUsed',
            field=models.IntegerField(blank=True, null=True, verbose_name=' რა რაოდენობის ქვანახშირი გამოიყენეთ გასული წლის განმავლობაში (კილოგრამებში)'),
        ),
        migrations.AlterField(
            model_name='post',
            name='woodUsed',
            field=models.IntegerField(blank=True, null=True, verbose_name=' რა რაოდენობის შეშა გამოიყენეთ გასული წლის განმავლობაში (კილოგრამებში)'),
        ),
    ]
