# Generated by Django 3.1.5 on 2021-09-11 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('footprint', '0006_auto_20210911_1525'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='totalAmount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True),
        ),
    ]
