# Generated by Django 3.1.5 on 2021-09-11 15:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('footprint', '0008_auto_20210911_1806'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='totalAmount',
        ),
    ]
