# Generated by Django 3.1.5 on 2021-09-11 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('footprint', '0009_remove_post_totalamount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='electricityGreen',
            field=models.IntegerField(choices=[(100, 'არა'), (75, 'დიახ')], default=100, verbose_name=' იყენებთ თუ არა მწვანე ენერგიას?'),
        ),
    ]
