# Generated by Django 3.1.5 on 2021-09-11 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('footprint', '0010_auto_20210911_2359'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='recyclePlastic',
            field=models.DecimalField(blank=True, choices=[(0, 'არა'), (14, 'დიახ')], decimal_places=2, default=0, max_digits=6, null=True, verbose_name=' აკეთებთ თუ არა პლასტმასის გადამუშავებას გარდა პოლიეთილენის პარკებისა?'),
        ),
    ]
